server:
  port: 10000

spring:
  application:
    name: mybatis-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scrapy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.common.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hand.cloud: debug
